# Makefile for helloworld

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=tc2
SRCS=tc2.c
BINDIR=/testbin
HOSTBINDIR=/hostbin

.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"
