# Makefile for helloworld

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=helloworld
SRCS=helloworld.c
BINDIR=/testbin
HOSTBINDIR=/hostbin

.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"
